from random import randint
temp = randint(0,3)
print("\n\n\n\n")
if temp == 0:
    print("\n")
    print("\t\t                                      |\                                                                                 ")
    print("\t\t    \033[91m-----------------------========<\033[97m|[XXXXXXXXXXXXXX]\033[91mSYN\033[97m)                                ")
    print("\t\t                                      |/                                                                                 ")
    print("\t\t                                                                     |\                                                 ")
    print("\t\t                                \033[91m------------------------==========<\033[97m|[XXXXXXXXXXXXXX]\033[91mSYN\033[97m)")
    print("\t\t                                                                     |/                                                 ")
    print("\t\t                                               |\                                                                     ")
    print("\t\t             \033[91m-----------------------========<\033[97m|[XXXXXXXXXXXXXX]\033[91mSYN\033[97m)                    ")
    print("\t\t                                               |/                                                                     ")
    print("\t\t                                                                                                                     ")
if temp == 1:
    print("\t\033[94m                                                                           ")
    print("\t\t\t[L]        [E][E][E]  [T][T][T]  []  [S][S][S]       [G][G][G][G]  [O][O][O][O]")
    print("\t\t\t[L]        [E]           [T]    |/   [S]             [G]           [O]      [O]")
    print("\t\t\t[L]        [E][E][E]     [T]         [S][S][S]       [G]   [G][G]  [O]      [O]")
    print("\t\t\t[L]        [E]           [T]               [S]       [G]      [G]  [O]      [O]")
    print("\t\t\t[L][L][L]  [E][E][E]     [T]         [S][S][S]       [G][G][G][G]  [O][O][O][O]")
elif temp == 2:
    print("\033[94m")
    print("\t\t _________      _________      _________      _________       _________      ___    ___      ")
    print("\t\t|\   ___   \   |\___   ___\   |\___   ___\   |\   ___   \    |\   ______\   |\  \  |\  \     ")
    print("\t\t\ \  \___\  \  \|__|\  \__|   \|__|\  \__|   \ \  \___\  \   \ \  \_____|   \ \  \_\_\__\    ")
    print("\t\t \ \   ___   \     \ \  \         \ \  \      \ \   ___   \   \ \  \         \ \   ___\_|   ")
    print("\t\t  \ \  \__|\  \     \ \  \         \ \  \      \ \  \__|\  \   \ \  \______   \ \  \__|\  \  ")
    print("\t\t   \ \__\ \ \__\     \ \__\         \ \  \      \ \__\ \ \__\   \ \_________\  \ \__\ \ \__\ ")
    print("\t\t    \|__|  \|__|      \|__|          \|__|       \|__|  \|__|    \|_________|   \|__|  \|__| ")
else:
    print("\033[94m")
    print("\t▇▇▇▇▇▇▇▇▇▇   ▇▇▇▇▇▇▇▇   ▇▇▇▇▇▇      ▇▇▇▇▇▇          ▇▇▇▇▇▇▇▇     ▇▇▇▇▇▇▇▇   ▇▇▇▇▇▇    ▇▇▇▇▇▇▇▇   ▇▇▇▇▇▇▇▇")
    print("\t        ▇▇   ▇▇         ▇▇   ▇▇    ▇▇    ▇▇         ▇▇     ▇▇    ▇▇         ▇▇   ▇▇   ▇▇         ▇▇      ")
    print("\t      ▇▇     ▇▇         ▇▇   ▇▇   ▇▇      ▇▇        ▇▇      ▇▇   ▇▇         ▇▇   ▇▇   ▇▇         ▇▇      ")
    print("\t    ▇▇       ▇▇▇▇▇▇▇▇   ▇▇▇▇▇▇    ▇▇      ▇▇        ▇▇      ▇▇   ▇▇▇▇▇▇▇▇   ▇▇▇▇▇▇    ▇▇▇▇▇▇▇▇   ▇▇▇▇▇▇▇▇")
    print("\t  ▇▇         ▇▇         ▇▇ ▇▇     ▇▇      ▇▇        ▇▇      ▇▇   ▇▇         ▇▇ ▇▇     ▇▇         ▇▇      ")
    print("\t▇▇           ▇▇         ▇▇  ▇▇     ▇▇    ▇▇         ▇▇     ▇▇    ▇▇         ▇▇  ▇▇    ▇▇         ▇▇      ")
    print("\t▇▇▇▇▇▇▇▇▇▇   ▇▇▇▇▇▇▇▇   ▇▇   ▇▇     ▇▇▇▇▇▇          ▇▇▇▇▇▇▇▇     ▇▇▇▇▇▇▇▇   ▇▇   ▇▇   ▇▇▇▇▇▇▇▇   ▇▇▇▇▇▇▇▇")
print("\n\n\n\t\033[97mFirst of all, thank you for using Zero Degree Attack&Reconnaissance Framework!\n")
print("\t\t     \033[97mVersion\033[94m = \033[97m[\033[94m2023.0.00             \033[97m]")
print("\t\t      \033[97mE-mail\033[94m = \033[97m[\033[94mkaliljw@163.com       \033[97m]")
print("\t\t      \033[97mE-mail\033[94m = \033[97m[\033[94mkaliljw@outlook.com   \033[97m]")
print("\t\t      \033[97mGithub\033[94m = \033[97m[\033[94mBlackCodeStorm        \033[97m]")
print("\t\t     \033[97mModules\033[94m = \033[97m[\033[94m1                     \033[97m]")
print("\n\n\tWe want to break all security!          ")
print("")
print("")