from random import randint
temp = randint(0,5)
print("\n\n\n\n")
if temp == 0:
    print("\n")
    print("\t\t                                      |\                                                                                 ")
    print("\t\t    \033[91m-----------------------========<\033[97m|[XXXXXXXXXXXXXX]\033[91mSYN\033[97m)                                ")
    print("\t\t                                      |/                                                                                 ")
    print("\t\t                                                                     |\                                                 ")
    print("\t\t                                \033[91m------------------------==========<\033[97m|[XXXXXXXXXXXXXX]\033[91mSYN\033[97m)")
    print("\t\t                                                                     |/                                                 ")
    print("\t\t                                               |\                                                                     ")
    print("\t\t             \033[91m-----------------------========<\033[97m|[XXXXXXXXXXXXXX]\033[91mSYN\033[97m)                    ")
    print("\t\t                                               |/                                                                     ")
    print("\t\t                                                                                                                     ")
elif temp == 1:
    print("\t\033[94m                                                                           ")
    print("\t\t\t[L]        [E][E][E)  (T][T][T)  []  /S][S][S)       /G][G][G][G)  /O][O][O][O\\")
    print("\t\t\t[L]        [E]           [T]    |/   [S]             [G]           [O]      [O]")
    print("\t\t\t[L]        [E][E][E)     [T]         \S][S][S\       [G]   (G][G\  [O]      [O]")
    print("\t\t\t[L]        [E]           [T]               [S]       [G]      [G]  [O]      [O]")
    print("\t\t\t[L][L][L)  [E][E][E)     [T]         (S][S][S/       \G][G][G][G/  \O][O][O][O/")
elif temp == 2:
    print("\033[94m")
    print("\t\t _________      _________      _________      _________       _________      ___    ___      ")
    print("\t\t|\   ___   \   |\___   ___\   |\___   ___\   |\   ___   \    |\   ______\   |\  \  |\  \     ")
    print("\t\t\ \  \___\  \  \|__|\  \__|   \|__|\  \__|   \ \  \___\  \   \ \  \_____|   \ \  \_\_\__\    ")
    print("\t\t \ \   ___   \     \ \  \         \ \  \      \ \   ___   \   \ \  \         \ \   ___\_|   ")
    print("\t\t  \ \  \__|\  \     \ \  \         \ \  \      \ \  \__|\  \   \ \  \______   \ \  \__|\  \  ")
    print("\t\t   \ \__\ \ \__\     \ \__\         \ \  \      \ \__\ \ \__\   \ \_________\  \ \__\ \ \__\ ")
    print("\t\t    \|__|  \|__|      \|__|          \|__|       \|__|  \|__|    \|_________|   \|__|  \|__| ")
elif temp == 3:
    print("\033[97m ")
    print("\t\t                     _ooOoo_                                                       ")
    print("\t\t                    o8888888o                                                      ")
    print("\t\t                    88\" . \"88                                                    ")
    print("\t\t                    (| -_- |)                                                      ")
    print("\t\t                    O\  =  /O                                                      ")
    print("\t\t                _____/`---`\_____                                                  ")
    print("\t\t              .`   \\\\|     |//   `.                                              ")
    print("\t\t             /   \\\\|||  :  |||//   \                                             ")
    print("\t\t            /   _||||| -:- |||||-   \                                              ")
    print("\t\t            |    | \\\\\\  -  /// |    |                                           ")
    print("\t\t            |  \_|  ''\---/''  |    |                                              ")
    print("\t\t            \  .-\___  `.`  ___/-.  /                                              ")
    print("\t\t           __`. .`   /--.--\   `. .`__                                             ")
    print("\t\t       .\"\" `<  `.____\_<|>_/____.`  >` \"\".                                     ")
    print("\t\t      | | :      \`.;`\ _ /`;.`/      :  | |                                       ")
    print("\t\t      \  \ `-,    \_ __\ /__ _/    ,-`  /  /                                       ")
    print("\t\t\033[94m======\033[97m`-,\____`-,____\_____/____,-`______,-`\033[94m======\033[97m ")
    print("\t\t                     `=---=`                                                       ")
else:
    print("\033[94m")
    print("\t                         l(1,                      ,fCU[.                                           .{UU?                                                               ")
    print("\t                        j8$$x                     !o$$$8\"                                           c$$$m                                                              ")
    print("\t                      .Y$$$$f                    `b$$$$\                                           l@$$@-                                                               ")
    print("\t                     'J$$$$$Z^                   f$$$$r                                            -$$$d                                                                ")
    print("\t                    :O$$$p$$$O`                 ,W$$$n                                             1$$$n                                                                ")
    print("\t                   [*$$b? f$$$C.                j$$$L                          .;_1)?;             x$$$]                                        .i1/}+)(I               ")
    print("\t                 :Y$$&j'   c$$$n               `*$$Bi             ._}l      '_ch@$$$$80!         .f8$$Bl                                      iua$$&#@$$&}.             ")
    print("\t               'tM$$O!     .O$$${              }$$$Z             .J$$%+   ,ja$$*U/|O$$$p        _p$$$$#`         !|UwdJi                    +0@$b\!`'?8$$Bl             ")
    print("\t              ]k$$&\.       ^k$$&>             0$$$)             !$$$@> 'tM$@C-'   ^&$$L      ~Q$$wW$$Z       :tb$$$$$$h`                 ;J@$&\.     a$$m.             ")
    print("\t            lL$$$wl      .\"l+z$$$k\"           ,&$$8;             ?$$$Z <p$@Y!      ]@$%>   '[Z$$b};8$$r     !X8$BQ)ic$$$]                -#$$q!      {@$${            ")
    print("\t          'f&$$$Z~<?)fcQpo8$$$$$$$0.          ]$$$d              )$$$}\B$O>       >M$$(  ixo$$w}. ?$$$?   lXB$#rI   lB$$Y              <XB$$Y'      }8$$Bl              ")
    print("\t         <q$$$$$$$$$$$$$%*pCXc(Y$$$c          x$$$Y            ,jM$$$k$&(        ?M$8/ltp$$WX~    n$$8: \"n8$#t\"     'a$$o'          l/p@$$$v      .r@$$$@>            ")
    print("\t       ^uB$$$8hpOCzr|}+!,'     'Z$$$r         J$$$r          InW$%$$$$d!       ^nB$8Zm$$8Q{\"      q$$O [a$8n\"        X$$$\     `l}cb$$M$$$0      -p$%J%$$t        ,:  ")
    print("\t      }a$$$Bv;.                 \"w$$$n'       C$$$Y       '?CB$b[Y$$$m^      :\a$$$$$#J{,         ,&$$qU$$0!           lW$$@QXU0dM$$$av>j$$$/   \")p$BY! u$$W-    .lx&z")
    print("\t    >0$$$$m<                     \"Z$$$b?      |$$$%|\".'I[X*$$Z]. m$$$}   \"_fO&$$$#Qt<`           ]$$$$$W)            <m8$$$$$&kJ|!.  |$$$WXuZ8$hjI   \'Y$$$k00q*@Mj` ")
    print("\t\"~}CB$$$a).                       'c@$$$t     `0$$$$WaM$$$kr!   ^#$$B!  j8$$$8qx+^               J$$$$ql                :<__<l\"       ./hB$$&qr<.       -Uh&8WbY}^    ")
    print("\t+bB$$%d\^                           -0ap[      .)0oW&#dY(!.     ~$$$*`  >/vr?:                  \"&$$$Y`                                 'lil`             .^\"`        ")
    print("\t .;><I                                \'           \'\"\"\'          j$$$q                           .(0O)                                                              ")
    print("\t                                                                q$$$C                                                                                                   ")
    print("\t                                                               ;8$$$x                                                                                                   ")
    print("\t                                                               ]$$$@<                                                                                                   ")
    print("\t                                                               ;Ybm[                                                                                                    ")
print("\n\n\n    \033[97mFirst of all, thank you for using Zero Degree Attack&Reconnaissance Framework!\n")
print("\t\t     \033[97mVersion\033[94m = \033[97m[\033[94m1.0.00                \033[97m]")
print("\t\t      \033[97mE-mail\033[94m = \033[97m[\033[94mkaliljw@163.com       \033[97m]")
print("\t\t      \033[97mE-mail\033[94m = \033[97m[\033[94mkaliljw@outlook.com   \033[97m]")
print("\t\t      \033[97mGithub\033[94m = \033[97m[\033[94mBlackCodeStorm        \033[97m]")
print("\n\n\tWe want to break all security!          ")
print("")
print("")